### ISSUE TITLE
Improve overall styling of Jupyter integration

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/Jupyter#19]

**Comment by kcullion** [comment]
![icgc-jupyter-loginicgc jupyter login](https://user-images.githubusercontent.com/18424138/36225230-ff7be2f0-1197-11e8-83f9-6a8acbd17692.jpg)
![icgc-jupyter-loginicgc jupyter interface](https://user-images.githubusercontent.com/18424138/36225234-00f209de-1198-11e8-9a0a-51d38bbf8c1d.jpg)

Mockups of ICGC Jupyter login page and logo and slight interface changes.
Assets are ready in Zeplin and svgs/images sent to @lepsalex
