### ISSUE TITLE
Update Jupyter demo notebook with Score client

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/Jupyter#53]
**Issue:**

* On the [ICGC Jupyter notebooks hub](https://jupyterhub.cancercollaboratory.org/hub/login), the **mydata-demo.ipynb** notebook is still using the **icgc-storage-client**
* The notebook needs to be updated to use the new **Score client**
* See attached screenshots

**Fix:**

* Ensure demo notebook runs with Score client
* Replace all references in instructions to the **icgc-storage-client** with Score client

**Screenshots:**

* Notebook selection menu:

![incorrect - demo notebook still using icgc-storage-client 1](https://user-images.githubusercontent.com/40768946/49319546-56681400-f4cb-11e8-83cf-fa985290ea04.png)

* References in instructions (screenshot 1):

![incorrect - demo notebook still using icgc-storage-client 2](https://user-images.githubusercontent.com/40768946/49319675-faea5600-f4cb-11e8-9f19-99c665cff4bf.png)

* References in instructions (screenshot 2):

![incorrect - demo notebook still using icgc-storage-client 3](https://user-images.githubusercontent.com/40768946/49319680-ffaf0a00-f4cb-11e8-8946-f4ca861b137a.png)

**Comment by KevinFHartmann** [comment]
Notebook is updated; but doesn't run because FUSE requires docker to run with CAP_SYS_ADMIN. I still need to edit the configuration file for JupyterHub to spawn docker containers with the capability 'CAP_SYS_ADMIN'.
